language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" = "7.2" ]]; then PHPUNIT_FLAGS="--coverage-clover=build/logs/clover.xml"; else PHPUNIT_FLAGS=""; fi
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --dev

script:
  - vendor/bin/phpunit -v $PHPUNIT_FLAGS

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" = "7.2" ]]; then php vendor/bin/php-coveralls -v; fi
  - if [[ "$TRAVIS_PHP_VERSION" = "7.2" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
